apiVersion: 1

datasources:

- name: OpenNMS-Performance
  type: opennms-performance-datasource
  isDefault: true
  editable: true
  access: proxy
  url: http://opennms:8980/opennms
  basicAuth: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: admin

- name: OpenNMS-Entities
  type: opennms-entity-datasource
  editable: true
  access: proxy
  url: http://opennms:8980/opennms
  basicAuth: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: admin

- name: OpenNMS-Flow
  type: opennms-flow-datasource
  editable: true
  access: proxy
  url: http://opennms:8980/opennms
  basicAuth: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: admin
