apiVersion: 1

datasources:

- name: OpenNMS-Performance
  type: opennms-helm-performance-datasource
  isDefault: true
  editable: true
  access: proxy
  url: http://opennms:8980/opennms
  basicAuth: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: admin

- name: OpenNMS-Entities
  type: opennms-helm-entity-datasource
  editable: true
  access: proxy
  url: http://opennms:8980/opennms
  basicAuth: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: admin

- name: OpenNMS-Flow
  type: opennms-helm-flow-datasource
  editable: true
  access: proxy
  url: http://opennms:8980/opennms
  basicAuth: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: admin
